export const en = {
  Home: "Home",
  "Who Are We?": "Who Are We?",
  "Why Chose Us": "Why Chose Us",
  "Our Reliable Partners": "Our Reliable Partners",
  "Our Services Partners": "Our Services Partners",
  "Sign In": "Sign In",
  "Sign Up": "Sign Up",
  RU: "RU",
  "Effectively monetize all": "Effectively monetize all",
  "types and sources of ": "types and sources of ",
  traffic: "traffic",
  "Start earning today": "Start earning today",
  "Join Now": "Join Now",
  "Contact our manager after registration and get high":
    "Contact our manager after registration and get high",
  "rates on all offers.": "rates on all offers.",
  "Who we are?": "Who we are?",
  "HQtraff is an affiliate program in the gambling vertical with its own exclusive offers and more, founded by an arbitrage team with extensive experience and expertise, which they are ready to share with their partners.":
    "HQtraff is an affiliate program in the gambling vertical with its own exclusive offers and more, founded by an arbitrage team with extensive experience and expertise, which they are ready to share with their partners.",
  "Why Chose us?": "Why Chose us?",
  "Own products in Latam and CIS": "Own products in Latam and CIS",
  "Stable Payments": "Stable Payments",
  "Help at all stages of launch for beginners":
    "Help at all stages of launch for beginners",
  "Free creatives": "Free creatives",
  "Free apps for efficient strait": "Free apps for efficient strait",
  "Strong support of personal managers": "Strong support of personal managers",
  "Only converting offers": "Only converting offers",
  "Easy integration with any trackers": "Easy integration with any trackers",
  "Our reliable partners:": "Our reliable partners:",
  "They talk about us": "They talk about us",
  "We have been working with HQtraff since  2020 and are very satisfied with our cooperation. The guys have high-quality traffic that pays off, HQtraff is highly recommended!":
    "We have been working with HQtraff since  2020 and are very satisfied with our cooperation. The guys have high-quality traffic that pays off, HQtraff is highly recommended!",
  "We have been working with HQtraff for a very long time, we approach our work creatively and responsibly. Only positive  impression about our work, our products  are available in pp for one of the best  conditions on the market. We will be happy to continue working with you.":
    "We have been working with HQtraff for a very long time, we approach our work creatively and responsibly. Only positive  impression about our work, our products  are available in pp for one of the best  conditions on the market. We will be happy to continue working with you.",
  "Cooperation with HQtraff means pleasant and high-quality communication and fulfillment of all agreements. The guys always know what is needed to achieve our common goal and work fruitfully for the result. it’s a pleasure to work with them and see them develop from an arbitrage team into a full-fledged affiliate program. ":
    "Cooperation with HQtraff means pleasant and high-quality communication and fulfillment of all agreements. The guys always know what is needed to achieve our common goal and work fruitfully for the result. it’s a pleasure to work with them and see them develop from an arbitrage team into a full-fledged affiliate program. ",
  "A reliable tam, we have know the guys for a long time, they have extensive experience in the industry.":
    "A reliable tam, we have know the guys for a long time, they have extensive experience in the industry.",
  "Always happy to work with them.": "Always happy to work with them.",
  "Our Service partners:": "Our Service partners:",
  Adheart: "Adheart",
  "Promo code:": "Promo code:",
  "Adheart is a service for collecting and analyzing advertising creatives on the Fb network and related platforms. AdHeart is currently simply irreplaceable due to its price and quality of service.":
    "Adheart is a service for collecting and analyzing advertising creatives on the Fb network and related platforms. AdHeart is currently simply irreplaceable due to its price and quality of service.",
  "-15% on the first payment": "-15% on the first payment",
  HQTRAFF: "HQTRAFF",
  "Go to the": "Go to the",
  Site: "Site",
  "Adspect ": "Adspect ",
  "Promo code:": "Promo code:",
  "Go to the": "Go to the",
  Site: "Site",
  "Adspect is a cloaking service. Based on JS fingerprinting and VLA machine learning with built-in white generators. Includes several competing services and a REST API for automation.":
    "Adspect is a cloaking service. Based on JS fingerprinting and VLA machine learning with built-in white generators. Includes several competing services and a REST API for automation.",
  "-15% on the first payment": "-15% on the first payment",
  HQTRAFF: "HQTRAFF",
  Adspy: "Adspy",
  "Free on the first payment": "Free on the first payment",
  "Promo code:": "Promo code:",
  "Go to the": "Go to the",
  Site: "Site",
  "AdSpy is the largest ad database in the world.":
    "AdSpy is the largest ad database in the world.",
  HQTRAFF: "HQTRAFF",
  "Cloaking house": "Cloaking house",
  "Promo code:": "Promo code:",
  "Go to the": "Go to the",
  Site: "Site",
  "Cloud service for filtering unwanted traffic and protection from bans. Traffic filtering using Machine Learning technologies. Easy integration in two minutes!":
    "Cloud service for filtering unwanted traffic and protection from bans. Traffic filtering using Machine Learning technologies. Easy integration in two minutes!",
  "-30% on the first payment": "-30% on the first payment",
  HQTRAFF: "HQTRAFF",
  Dolphin: "Dolphin",
  "Promo code:": "Promo code:",
  "Go to the": "Go to the",
  Site: "Site",
  "Dolphin is a service for automating work. Manage all accounts from one tab, comment moderation, ad autofill and teamwork":
    "Dolphin is a service for automating work. Manage all accounts from one tab, comment moderation, ad autofill and teamwork",
  "-20% on the first payment": "-20% on the first payment",
  HQTRAFF: "HQTRAFF",
  "Dolphin{anty}": "Dolphin{anty}",
  "Promo code:": "Promo code:",
  "Go to the": "Go to the",
  Site: "Site",
  "Dolphin{anty} is a reliable and convenient antidetect browser with a large number of substitutions. Automation of processes and the possibility of teamwork.":
    "Dolphin{anty} is a reliable and convenient antidetect browser with a large number of substitutions. Automation of processes and the possibility of teamwork.",
  "-20% on the first payment": "-20% on the first payment",
  HQTRAFF: "HQTRAFF",
  "EPN.net": "EPN.net",
  "Promo code:": "Promo code:",
  "Go to the": "Go to the",
  Site: "Site",
  "Virtual cards 18 BIN of American banks, fit perfectly with advertising cabinets, keep a high span. Free cards in any quantity, transparent commissions - from 2%, team access, auto-replenishment.":
    "Virtual cards 18 BIN of American banks, fit perfectly with advertising cabinets, keep a high span. Free cards in any quantity, transparent commissions - from 2%, team access, auto-replenishment.",
  "-20% on the first payment": "-20% on the first payment",
  HQTRAFF: "HQTRAFF",
  1: "1",
  "Join and earn with us!": "Join and earn with us!",
  "If you are a webmaster or an advertiser looking for a reliable network for cooperation, we are glad to welcome you to our team.":
    "If you are a webmaster or an advertiser looking for a reliable network for cooperation, we are glad to welcome you to our team.",
  "Contact Us": "Contact Us",
  "Web Masters": "Web Masters",
  Advertisers: "Advertisers",
  "Head of Affiliate": "Head of Affiliate",
  Support: "Support",
  HQtraff_Egor: "HQtraff_Egor",
  HQ_Support: "HQ_Support",
  Support: "Support",
  HQ_Support: "HQ_Support",
  Language: "Language",
  Navigation: "Navigation",
  RU: "RU",
  Home: "Home",
  EN: "EN",
  "Who Are We?": "Who Are We?",
  UA: "UA",
  "Why Chose Us": "Why Chose Us",
  "Our Reliable Partners": "Our Reliable Partners",
  "Our Services Partners": "Our Services Partners",
  "all right reserved": "all right reserved",
  "hqtraffpartners@gmail.com": "hqtraffpartners@gmail.com",
};
