export const ru = {
  Home: "Home",
  "Who Are We?": "Кmо мы maкue",
  "Why Chose Us": "Почему выбирают нас",
  "Our Reliable Partners": "Наши надежные партнеры",
  "Our Services Partners": "Наши партнеры по оказанию услуг",
  "Sign In": "Вход",
  "Sign Up": "Регистрация",
  RU: "RU",
  "Effectively monetize all": "Эффективно монетизируй все ",
  "types and": " виды и ",
  "sources of": "источники ",
  traffic: "трафика",
  "Start earning today": "Начни зарабатывать уже сегодня.",
  "Join Now": "Присоединяйтесь сейчас",
  "Contact our": "Свяжись с нашим ",
  manager: "менеджером",
  "after registration and": "после регистрации и ",
  "get high rates on all offers.": "получай высокие ставки на все оффера.",
  "Who we are?": "Кmо мы maкue",
  "HQtraff is an affiliate program in the gambling vertical with its own exclusive offers and more, founded by an arbitrage team with extensive experience and expertise, which they are ready to share with their partners.":
    "HQtraff - партнерская программа в gambling-вертикали с собственными эксклюзивными офферами и не только, основанная арбитражной командой с большим опытом и экспертизой, которой готовы делиться со своими партнерами.",
  "Why Chose us?": "Почему выбирают нас?",
  "Own products in Latam and CIS": "собственные продукты на Латам и СНГ",
  "Stable Payments": " стабильные выплаты",
  "Help at all stages of launch for beginners":
    " помощь на всех этапах запуска для новичков",
  "Free creatives": " бесплатные креативы",
  "Free apps for efficient strait":
    " бесплатные приложения для эффективного пролива",
  "Strong support of personal managers":
    " сильная поддержка персональных менеджеров",
  "Only converting offers": " только конвертящие офферы",
  "Easy integration with any trackers":
    " простая интеграция с любыми трекерами",
  "Наши надежные партнеры:": "Наши надежные партнеры:",
  "Reviews from our partners": "Отзывы наших партнеров",
  "We have been working with HQtraff since  2020 and are very satisfied with our cooperation. The guys have high-quality traffic that pays off, HQtraff is highly recommended!":
    "С HQtraff работаем уже с 2020 года и очень довольны нашим сотрудничеством. У ребят качественный траф на разные гео. Если вам нужен траф, который окупается - вам к HQtraff, очень рекомендуем!",
  "We have been working with HQtraff for a very long time, we approach our work	creatively and responsibly. Only positive	impression about our work, our products	are available in pp for one of the best conditions on the market. We will be happy to continue working with you.":
    "Работаем с HQtraff очень долго, подходят к своей работе креативно и ответственно. Только позитивные впечатления о нашей работе, наши продукты доступны в пп по одним из самых лучших условий на рынке. Будем рады и дальше работать вместе с вами",
  "Cooperation with HQtraff means pleasant and high-quality communication and fulfillment of all agreements. The guys always know what is needed to achieve our common goal and work fruitfully for the result. it’s a pleasure to work with them and see them develop from an arbitrage team into a full-fledged affiliate program. ":
    "Сотрудничество с HQtraff — это приятное и качественное общение и выполнение всех договоренностей. Ребята всегда знают, что нужно для достижения нашей общей цели и плодотворно работают на результат. Приятно сотрудничать с ними и видеть их развитие из арбитражной команды в полноценную партнёрскую программу.",
  "A reliable tam, we have know the guys for a long time, they have extensive experience in the industry.":
    "Надежная команда, давно знаем ребят, имеют большой опыт в индустрии. Всегда рады сотрудничать с ними",
  "Always happy to work with them.": "Всегда рады работать с ними.",
  "Our Service partners:": "Наши партнеры по оказанию услуг:",
  Adheart: "Adheart",
  "Promo code:": "Промокод",
  "Adheart is a service for collecting and analyzing advertising creatives on the Fb network and related platforms. AdHeart is currently simply irreplaceable due to its price and quality of service.":
    "Adheart — это сервис для сбора и аналитики рекламных креативов в сети Fb, и сопутствующих ему платформ.. AdHeart на данный момент просто незаменим за счет своей цены и качества сервиса.",
  "-15% on the first payment": "-15% на первый платеж",
  HQTRAFF: "HQTRAFF",
  "Go to the": "Перейти на",
  Site: "Сайт",
  "Adspect ": "Adspect ",
  "Promo code:": "Промокод",
  "Go to the": "Перейти на",
  Site: "Сайт",
  "Adspect is a cloaking service. Based on JS fingerprinting and VLA machine learning with built-in white generators. Includes several competing services and a REST API for automation.":
    "Adspect — сервис клоакинга. На базе JS-фингерпринтинга и машинного обучения VLA со встроенными генераторами вайтов. Включает в себя несколько конкурирующих сервисов и REST API для автоматизации",
  "-15% on the first payment": "-15% на первый платеж",
  HQTRAFF: "HQTRAFF",
  Adspy: "Adspy",
  "Free on the first payment": "Бесплатно при первом платеже",
  "Promo code:": "Промокод",
  "Go to the": "Перейти на",
  Site: "Сайт",
  "AdSpy is the largest ad database in the world.":
    "AdSpy — крупнейшая в мире база данных объявлений.",
  HQTRAFF: "HQTRAFF",
  "Cloaking house": "Cloaking house",
  "Promo code:": "Промокод",
  "Go to the": "Go to the",
  Site: "Site",
  "Cloud service for filtering unwanted traffic and protection from bans. Traffic filtering using Machine Learning technologies. Easy integration in two minutes!":
    "Облачный сервис для фильтрации нежелательного трафика и защиты от банов. Фильтрация трафика по технологиям Machine Learning. Простая интеграция за две минуты!",
  "-30% on the first payment": "-30% на первый платеж",
  HQTRAFF: "HQTRAFF",
  Dolphin: "Dolphin",
  "Promo code:": "Промокод",
  "Go to the": "Перейти на",
  Site: "Сайт",
  "Dolphin is a service for automating work. Manage all accounts from one tab, comment moderation, ad autofill and teamwork":
    "Dolphin — сервис для автоматизации работы. Управление всеми аккаунтами из одной вкладки, модерация комментариев, автозалив рекламы и командная работа",
  "-20% on the first payment": "-30% на первый платеж",
  HQTRAFF: "HQTRAFF",
  "Dolphin{anty}": "Dolphin{anty}",
  "Promo code:": "Промокод",
  "Go To The Site": "Перейти на Сайт",

  "Dolphin{anty} is a reliable and convenient antidetect browser with a large number of substitutions. Automation of processes and the possibility of teamwork.":
    "Dolphin{anty} — надёжный и удобный антидетект браузер с большим количеством подмен. Автоматизация процессов и возможность командной работы.",
  "-20% on the first payment": "-20% на первый платеж",
  HQTRAFF: "HQTRAFF",
  "EPN.net": "EPN.net",
  "Promo code:": "Промокод",
  "Go to the": "Перейти на",
  Site: "Сайт",
  "Virtual cards 18 BIN of American banks, fit perfectly with advertising cabinets, keep a high span. Free cards in any quantity, transparent commissions - from 2%, team access, auto-replenishment.":
    "Виртуальные карты 18 BIN американских банков, отлично вяжутся с рекламными кабинетами, держат высокий спенд.",
  "-20% on the first payment": "-20% на первый платеж",
  HQTRAFF: "HQTRAFF",
  1: "1",
  "Join and earn with us!": "Присоединяйтесь и зарабатывайте с нами!",
  "If you are a webmaster or an advertiser looking for a reliable network for cooperation, we are glad to welcome you to our team.":
    "Если вы вебмастер или рекламодатель, ищущий надежную сеть для сотрудничества — рады приветствовать вас в нашей команде.",
  "Contact Us": "Связаться с нами",
  "Web Masters": "Вебмастерам ",
  Advertisers: "Рекламодателям ",
  "Head of Affiliate": "Руководитель отдела по работе с партнерами",
  Support: "Поддержка",
  HQtraff_Egor: "HQ_Support",
  HQ_Support: "HQtraff_Egor",
  Support: "Поддержка",
  HQ_Support: "HQ_Support",
  Language: "Язык",
  Navigation: "Навигация",
  RU: "RU",
  Home: "Главная",
  EN: "EN",
  "Who Are We?": "Кmо мы maкue",
  UA: "UA",
  "Why Chose Us": "Почему выбирают нас",
  "Our Reliable Partners": "Наши надежные партнеры",
  "Our Services Partners": "Наши сервис партнеры",
  "all right reserved": "все права защищены",
  "hqtraffpartners@gmail.com": "hqtraffpartners@gmail.com",
  "An indispensable set of tools for working with advertising":
    "Незаменимый набор инструментов для работы с рекламой",
  "Indigo is an anti-detect browser for comfortable and safe work of solos and teams with all types of anti-fraud systems.":
    "Indigo — антидетект браузер для комфортной и безопасной работы соло и команд со всеми типами антифрод систем",
  "iRent Market is a bot for renting applications in the AppStore.":
    "Сервис по аренде и покупке iOS-приложений для азартных игр и ставок. Мы создаем веб-приложения iOS для FB, TT, In-App, UAC и других источников.",
  "Multifunctional PWA app builder for any vertical":
    "Сервис для создания PWA-приложений для Gambling, Betting, Dating, Nutra, Crypto и других ниш.",
  "Keitaro is a universal tracker for online marketing. Work without cookies, reports based on 30+ metrics, domain parking, teamwork and many other options for profitable work.":
    "Keitaro — универсальный трекер для интернет-маркетинга. Работа без cookies, отчеты на основе 30+ метрик, парковка доменов, работа в команде и многие другие опции для профитной работы.",
  "Individual proxies for solving any problems":
    "Индивидуальные прокси для решения любых задач",
};
