export const ru = {
  Home: "Home",
  "Who Are We?": "Who Are We?",
  "Why Chose Us": "Why Chose Us",
  "Our Reliable Partners": "Our Reliable Partners",
  "Our Services Partners": "Our Services Partners",
  "Sign In": "Sign In",
  "Sign Up": "Sign Up",
  RU: "RU",
  "Effectively monetize all": "Эффективно монетизировать все",
  "types and": " типы и ",
  "sources of": "источники ",
  traffic: "трафика",
  "Start earning today": "Начните зарабатывать сегодня",
  "Join Now": "Присоединяйтесь сейчас",
  "Contact our": "Свяжитесь с ",
  manager: "менеджером",
  "after registration and": "нашим  после регистрации и ",
  "get high rates on all offers.":
    "получите высокие ставки на все предложения.",
  "Who we are?": "Кто мы?",
  "HQtraff is an affiliate program in the gambling vertical with its own exclusive offers and more, founded by an arbitrage team with extensive experience and expertise, which they are ready to share with their partners.":
    "HQtraff - это партнерская программа в вертикали азартных игр с собственными эксклюзивными предложениями и многим другим, основанная арбитражной командой с большим опытом и знаниями, которыми они готовы поделиться со своими партнерами.",
  "Why Chose us?": "Почему выбрали нас?",
  "Own products in Latam and CIS": "Собственные продукты в Латаме и СНГ",
  "Stable Payments": "Стабильные платежи",
  "Help at all stages of launch for beginners":
    "Помощь на всех этапах запуска для начинающих",
  "Free creatives": "Свободные творцы",
  "Free apps for efficient strait":
    "Бесплатные приложения для эффективного пролива",
  "Strong support of personal managers":
    "Сильная поддержка персональных менеджеров",
  "Only converting offers": "Только конвертирующие предложения",
  "Easy integration with any trackers": "Простая интеграция с любыми трекерами",
  "Our reliable partners:": "Наши надежные партнеры:",
  "Reviews from our partners": "Отзывы наших партнеров",
  "We have been working with HQtraff since  2020 and are very satisfied with our cooperation. The guys have high-quality traffic that pays off, HQtraff is highly recommended!":
    "Мы работаем с HQtraff с 2020 года и очень довольны нашим сотрудничеством. У ребят качественный трафик, который окупается, HQtraff очень рекомендуем!",
  "We have been working with HQtraff for a very long time, we approach our work	creatively and responsibly. Only positive	impression about our work, our products	are available in pp for one of the best conditions on the market. We will be happy to continue working with you.":
    "Мы работаем с HQtraff в течение очень долгое время, мы подходим к нашей работе  творчески и ответственно. Только положительное  впечатление о нашей работе, наши продукты  доступны в пп по одним из лучших условиях на рынке. Мы будем рады продолжить сотрудничество с Вами.",
  "Cooperation with HQtraff means pleasant and high-quality communication and fulfillment of all agreements. The guys always know what is needed to achieve our common goal and work fruitfully for the result. it’s a pleasure to work with them and see them develop from an arbitrage team into a full-fledged affiliate program. ":
    "Сотрудничество с HQtraff - это приятное и качественное общение и выполнение всех договоренностей. Ребята всегда знают, что нужно для достижения нашей общей цели и плодотворно работают на результат. с ними приятно работать и видеть, как из арбитражной команды они превращаются в полноценную партнерскую программу.",
  "A reliable tam, we have know the guys for a long time, they have extensive experience in the industry.":
    "Надежная тама, мы давно знаем ребят, у них большой опыт работы в отрасли.",
  "Always happy to work with them.": "Всегда рады работать с ними.",
  "Our Service partners:": "Наши партнеры по оказанию услуг:",
  Adheart: "Adheart",
  "Promo code:": "Промокод",
  "Adheart is a service for collecting and analyzing advertising creatives on the Fb network and related platforms. AdHeart is currently simply irreplaceable due to its price and quality of service.":
    "Adheart - это сервис для сбора и анализа рекламных креативов в сети Fb и связанных с ней платформах. В настоящее время AdHeart просто незаменим благодаря своей цене и качеству услуг.",
  "-15% on the first payment": "-15% на первый платеж",
  HQTRAFF: "HQTRAFF",
  "Go to the": "Перейти на",
  Site: "Сайт",
  "Adspect ": "Adspect ",
  "Promo code:": "Промокод",
  "Go to the": "Перейти на",
  Site: "Сайт",
  "Adspect is a cloaking service. Based on JS fingerprinting and VLA machine learning with built-in white generators. Includes several competing services and a REST API for automation.":
    "Adspect - это сервис маскировки. Основан на JS fingerprinting и машинном обучении VLA со встроенными генераторами белого цвета. Включает несколько конкурирующих сервисов и REST API для автоматизации.",
  "-15% on the first payment": "-15% на первый платеж",
  HQTRAFF: "HQTRAFF",
  Adspy: "Adspy",
  "Free on the first payment": "Бесплатно при первом платеже",
  "Promo code:": "Промокод",
  "Go to the": "Перейти на",
  Site: "Сайт",
  "AdSpy is the largest ad database in the world.":
    "AdSpy - это самая большая база данных объявлений в мире.",
  HQTRAFF: "HQTRAFF",
  "Cloaking house": "Cloaking house",
  "Promo code:": "Промокод",
  "Go to the": "Go to the",
  Site: "Site",
  "Cloud service for filtering unwanted traffic and protection from bans. Traffic filtering using Machine Learning technologies. Easy integration in two minutes!":
    "Облачный сервис для фильтрации нежелательного трафика и защиты от запретов. Фильтрация трафика с использованием технологий машинного обучения. Простая интеграция за две минуты!",
  "-30% on the first payment": "-30% на первый платеж",
  HQTRAFF: "HQTRAFF",
  Dolphin: "Dolphin",
  "Promo code:": "Промокод",
  "Go to the": "Перейти на",
  Site: "Сайт",
  "Dolphin is a service for automating work. Manage all accounts from one tab, comment moderation, ad autofill and teamwork":
    "Облачный сервис для фильтрации нежелательного трафика и защиты от запретов. Фильтрация трафика с использованием технологий машинного обучения. Простая интеграция за две минуты!",
  "-20% on the first payment": "-30% на первый платеж",
  HQTRAFF: "HQTRAFF",
  "Dolphin{anty}": "Dolphin{anty}",
  "Promo code:": "Промокод",
  "Go to the": "Перейти на",
  Site: "Сайт",
  "Dolphin{anty} is a reliable and convenient antidetect browser with a large number of substitutions. Automation of processes and the possibility of teamwork.":
    "Dolphin{anty} - надежный и удобный антидетекторный браузер с большим количеством замен. Автоматизация процессов и возможность командной работы.",
  "-20% on the first payment": "-20% на первый платеж",
  HQTRAFF: "HQTRAFF",
  "EPN.net": "EPN.net",
  "Promo code:": "Промокод",
  "Go to the": "Перейти на",
  Site: "Сайт",
  "Virtual cards 18 BIN of American banks, fit perfectly with advertising cabinets, keep a high span. Free cards in any quantity, transparent commissions - from 2%, team access, auto-replenishment.":
    "Виртуальные карты 18 BIN американских банков, прекрасно вписываются в рекламные витрины, держат высокий пролет. Бесплатные карты в любом количестве, прозрачные комиссии - от 2%, командный доступ, автопополнение.",
  "-20% on the first payment": "-20% на первый платеж",
  HQTRAFF: "HQTRAFF",
  1: "1",
  "Join and earn with us!": "Присоединяйтесь и зарабатывайте вместе с нами!",
  "If you are a webmaster or an advertiser looking for a reliable network for cooperation, we are glad to welcome you to our team.":
    "Если вы вебмастер или рекламодатель, ищущий надежную сеть для сотрудничества, мы рады приветствовать вас в нашей команде.",
  "Contact Us": "Связаться с нами",
  "Web Masters": "Веб-мастера",
  Advertisers: "Рекламодатели",
  "Head of Affiliate": "Руководитель отдела по работе с партнерами",
  Support: "Поддержка",
  HQtraff_Egor: "HQ_Support",
  HQ_Support: "HQtraff_Egor",
  Support: "Поддержка",
  HQ_Support: "HQ_Support",
  Language: "Язык",
  Navigation: "Навигация",
  RU: "RU",
  Home: "Главная",
  EN: "EN",
  "Who Are We?": "Кто мы?",
  UA: "UA",
  "Why Chose Us": "Почему выбирают нас",
  "Our Reliable Partners": "Наши надежные партнеры",
  "Our Services Partners": "Наши партнеры по оказанию услуг",
  "all right reserved": "все права защищены",
  "hqtraffpartners@gmail.com": "hqtraffpartners@gmail.com",
  "An indispensable set of tools for working with advertising":
    "Незаменимый набор инструментов для работы с рекламой",
  "Indigo is an anti-detect browser for comfortable and safe work of solos and teams with all types of anti-fraud systems.":
    "Indigo — браузер-антидетект для комфортной и безопасной работы соло и команд со всеми видами антифрод-систем.",
  "iRent Market is a bot for renting applications in the AppStore.":
    "iRent Market — бот для аренды приложений в AppStore.",
  "Multifunctional PWA app builder for any vertical":
    "Многофункциональный конструктор приложений PWA для любой вертикали",
  "Keitaro is a universal tracker for online marketing. Work without cookies, reports based on 30+ metrics, domain parking, teamwork and many other options for profitable work.":
    "Keitaro — универсальный трекер для интернет-маркетинга. Работа без куки, отчеты по 30+ метрикам, парковка домена, командная работа и множество других опций для выгодной работы.",
  "Individual proxies for solving any problems":
    "Индивидуальные прокси для решения любых задач",
};
